apiVersion: v1
kind: ConfigMap
metadata:
  name: pdcm-submission-dev-configmap
  namespace: pdcm-validator-dev
data:
  REACT_APP_PDCM_LECTERN_VALIDATOR: "http://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:32002/validation/upload-excel"