apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdcm-submission-dev
  namespace: pdcm-validator-dev
spec:
  replicas: 1  # Number of replicas/pods to run
  selector:
    matchLabels:
      app: pdcm-submission-dev
  template:
    metadata:
      labels:
        app: pdcm-submission-dev
    spec:
      containers:
        - name: pdcm-submission
          image: pdxfinder/pdcm-submission:develop
          imagePullPolicy: Always
          ports:
            - containerPort: 3000  # Port your Docusaurus app is listening on
          resources:
            limits:
              cpu: "0.5"    # The maximum CPU the container can use (e.g., 0.5 CPU core)
              memory: "512Mi"  # The maximum memory the container can use (e.g., 512 megabytes)
            requests:
              cpu: "0.2"    # The guaranteed minimum CPU the container needs (e.g., 0.2 CPU core)
              memory: "256Mi"  # The guaranteed minimum memory the container needs (e.g., 256 megabytes)
          