apiVersion: v1
kind: Service
metadata:
  name: pdcm-submission-service
  labels:
    app: pdcm-submission
  namespace: pdcm-validator
spec:
  selector:
    app: pdcm-submission
  ports:
    - protocol: TCP
      port: 3000  # Port to expose on the Service
      targetPort: 3000  # Port your Docusaurus app is listening on inside the container
      nodePort: 31319
  type: NodePort
status:
  loadBalancer: {}  # Expose the Service using a LoadBalancer (for public access)
